name: Rain Alert test

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-rain-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run rain alert
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
        run: |
          python rain_alert.py
